import {
  Send,
  Star,
  Zap,
  Car,
  MonitorPlay,
  Plane,
  Truck,
  ListFilter,
  Utensils,
  Sofa,
  BookOpen,
  Banknote,
  Dumbbell,
  Palette,
  School,
  Heart,
  Gem,
  Code,
  Scissors,
  Gift,
  Factory,
  Lightbulb,
  Microscope,
  MapPin,
  Ruler,
  Headphones,
  Feather,
  Handshake,
  Shield,
  Globe,
  ShoppingBag,
  GlobeIcon,
} from "lucide-react";

export const itemTypes = [
  { value: "all", label: "All Categories", icon: GlobeIcon },
  { value: "tech", label: "Tech & Gadgets", icon: Zap },
  { value: "auto", label: "Automotive", icon: Car },
  { value: "media", label: "Movies & Media", icon: MonitorPlay },
  { value: "travel", label: "Travel / Destinations", icon: Plane },
  { value: "infrastructure", label: "Roads / Places", icon: Truck },
  { value: "food", label: "Food & Restaurants", icon: Utensils },
  { value: "home", label: "Home & Furniture", icon: Sofa },
  { value: "books", label: "Books & Literature", icon: BookOpen },
  { value: "finance", label: "Finance & Services", icon: Banknote },
  { value: "health", label: "Health & Fitness", icon: Dumbbell },

  { value: "art", label: "Art & Supplies", icon: Palette },
  { value: "education", label: "Learning & Courses", icon: School },
  { value: "dating", label: "Dating Apps & Services", icon: Heart },
  { value: "jewelry", label: "Jewelry & Luxury Goods", icon: Gem },
  { value: "software", label: "Software & Apps", icon: Code },
  { value: "beauty", label: "Beauty & Personal Care", icon: Scissors },
  { value: "toys", label: "Toys & Games", icon: Gift },
  { value: "industrial", label: "Industrial & Tools", icon: Factory },
  { value: "startup", label: "Startups & Concepts", icon: Lightbulb },
  { value: "science", label: "Science & Research", icon: Microscope },
  { value: "real_estate", label: "Real Estate & Housing", icon: MapPin },
  { value: "fashion", label: "Clothing & Apparel", icon: ShoppingBag },
  { value: "sports", label: "Sports Equipment", icon: Dumbbell }, // Reused icon
  { value: "music", label: "Music & Audio Gear", icon: Headphones }, // Reused icon
  { value: "pets", label: "Pet Supplies & Food", icon: Feather },
  { value: "legal", label: "Legal & Consulting", icon: Handshake },
  { value: "security", label: "Security & Antivirus", icon: Shield },
  { value: "gov", label: "Government Services", icon: Globe },
  { value: "measurement", label: "Tools & Measurement", icon: Ruler },
  { value: "other", label: "Other / Uncategorized", icon: ListFilter },
];
